version: '3.8'

services:
  app:
    build: 
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-local}
      - DATABASE_URL=postgres://${DB_USER:-yourdbuser}:${DB_PASSWORD:-yourdbpassword}@db:5432/${DB_NAME:-yourdbname}
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-yourdbname}
      - POSTGRES_USER=${DB_USER:-yourdbuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-yourdbpassword}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: